= Outline
:toc:

== Issue

* Which scientifically relevant problem is the starting point of the work and why is this a problem?
* What is the relevance of the problem under investigation?
* Why is it worth to pursue his problem?
* How can the individual aspects of the problem be presented systematically?

== Interest in Knowledge

* Why should this particular problem be addressed?
* Why this topic?
* What is original about your approach? (e.g. independence of the concept; presentation, consolidation or linking of individual aspects; commenting on existing knowledge, etc.).
* What additional scientific knowledge does the processing of the problem bring? Usually this expectation is only made for dissertations.

== Question

* To which central question should an answer be found or given in the work?
* Which concrete problem should be dealt with from which perspective and under what circumstances?

== Objectives and hypothesis

* What is the aim of the explanations?
* What should be proved or disproved?

== Theoretical reference

* Which theories, models or explanatory approaches should be referenced?
* Is there a focus on a specific theory/model that is just supplemented by others.
* Why are the selected theories/models/explanatory approaches used? Why does the application make sense and what is the explanatory power?

== State of research

* What scientific findings are already available on the subject?
* Which aspects of the topic have not yet been adequately or successfully dealt with?
* Can the topic be scientifically processed with reasonable effort?
* Are there conflicting or competing statements or statements in the literature? Interpretations? What are the most important positions there? This list must be as exhaustive as possible. No interpretations may be intentionally left out.
* Which position will be joined or which position will be developed?

== Method

* Which scientifc methods will be used to process the problem?
* Which methods can be used to appropriately process the (main) questions and hypotheses? (theoretical or empirical, primary or secondary analysis, qualitative or quantitative, discourse analysis or inquiry, a combination of methods, etc.).
* Why are the selected methods suitable for working on the topic?
* What level of knowledge does the writer/researcher have regarding the chosen methods?

== Materials

* Which material (eg which hardware or software), which data, which source should be used and why?
* Which material and which sources or data are already available?
* What information still needs to be determined in order to at least meet the minimum requirements for the topic?

== Outline

* Which aspects of the work should be dealt with and in which order?
* Why does this order make sense?

== About Bibliography

Searched google scholar for `rust high level synthesis`, looked at first 5 pages, copied all entries related to rust programming and HLS to bibliography. <<Har22>> <<Tak20>>

Searched google scholar for `llvm high level synthesis. <<Rog20>> <<Li20>> <<Lia23>>

Searched google scholar for `high level synthesis. <<Rot10>> <<Fer21>>

https://crates.io is the primary rust package registry. If someone has already done some work in rust it will be on there. I list crates with their name, description from cargo.toml, and date of last commit.

I tried to find projects that already do HLS from rust.

For all https://crates.io searches I looked at all results, selected everything that is related to generating RTL from rust, is not hardware specific, is not a opencl wrapper, is not related to interfacing with FPGAs, and is not a extension for another already listed result.


Searched https://crates.io 

* `high level synthesis`: <<verugent>>
* `hls`: -
* `fpga`: <<rust-hdl>> <<kaze>>
* `hld`: -

The only one of these crates that does something that is similar to HLS is rust-hdl, but that is more like a HDL and less HLS, because it only supports a limited subset of rust.

So there is no tool for performing HLS from rust on crates.io. As a 

.Google searches
[%collapsible]
====
Searches: 

* `rust to fpga`

I visited the following pages:

* https://users.rust-lang.org/t/rust-and-fpgas-is-it-possible/50033/5
** Reference to <<Tak20>>
** Reference to https://google.github.io/xls/[XLS^] which is a more generic solution
** Reference to https://github.com/llvm/circt[CIRCT^] which is a llvm project about Circuit IR Compilers and Tools. LLHD belongs to CIRCT.
** There apparently are already a few llvm ir to fpga tools. Very interesting link: https://llvm.org/devmtg/2014-10/Slides/Baker-CustomHardwareStateMachines.pdf
* https://www.reddit.com/r/rust/comments/fyd57q/q_rust_as_a_hardware_description_language_to_be/
** LLVM is probably the easiest way.
** _"My thinking is that Rust code would be much more efficient than OpenCL since it should naturally prevent latching."_
** https://www.chisel-lang.org/firrtl/[FIRRTL^] is called the _"most developed low-level HDL intermediate language"_ (2020)
** Also references <<Tak20>>
** Link the LLHD paper. I added it to my bib <<Sch20>>
* https://www.youtube.com/watch?v=TUDkKxAdeWk
** Maybe there is something interesting in this video, but I dont think so.
** TODO: watch
* https://ieeexplore.ieee.org/document/9292032
** The paper is related to <<verugent>>. Horrible english.
** Same author as <<Tak20>>
** Not related, because verugent is just a verilog builder, but does not do HLS.
* https://news.ycombinator.com/item?id=24354083
** About XLS
** XLS is a HDL that is based on Rust, I think
** https://google.github.io/xls/dslx_reference/[DSLX] is the language, XLS is just the framework
** https://github.com/google/xls/blob/main/xls/examples/dslx_intro/prefix_scan_equality.x[Some code]
** 
====

Through the google search I found XLS, which is probably similar to <<rust-hdl>>, but may have more HLS capabilities. It is not real Rust, but syntactically and semantically inspired by Rust.

TODO: investigate XLS

The only remaining way of synthesizing Rust I can think of is maybe with some port of opencl that also has a FPGA backend. If that would be the case than I probably would have found it in the previous google search. Most HPC frameworks like openmp build on top of opencl, so if opencl cannot bring Rust to FPGAs, they also wont be able to do that. Anyway I will now specifically search for `rust opencl`.

opencl has a rust port, but the kernels still have to be written in C++. Maybe there is another path to fpgas by compiling to a shader language and then to fpga somehow. trisycl.

There is currently no way of synthesising RTL from normal Rust directly. With rust-hdl and XLS there are two approaches, but both are limited indifferent ways. I dont think I missed anything.

Next step would be to look at some intermediate representations.

[bibliography]
== Bibliography

* [[[Har22]]]
Hardin, David,
_Hardware/Software Co-Assurance using the Rust Programming Language and ACL2_,
arXiv preprint arXiv:2205.11709,
2022.
https://arxiv.org/abs/2205.11709v1[🔗^]

* [[[Tak20]]]
Takano, Keisuke and Oda, Tetsuya and Kohata, Masaki,
_Design of a DSL for converting rust programming language into RTL_,
International Conference on Emerging Internetworking, Data & Web Technologies, 342-350,
2020.
https://link.springer.com/chapter/10.1007/978-3-030-39746-3_36[🔗^]

* [[[Rog20]]]
Rogers, Samuel and Slycord, Joshua and Baharani, Mohammadreza and Tabkhi, Hamed,
_gem5-SALAM: A System Architecture for LLVM-based Accelerator Modeling_,
2020 53rd Annual IEEE/ACM International Symposium on Microarchitecture (MICRO), 471-482,
2020.
https://ieeexplore.ieee.org/abstract/document/9251937[🔗^]

* [[[Li21]]]
Li, Rui and Berkley, Lincoln and Yang, Yihang and Manohar, Rajit,
_Fluid: An Asynchronous High-level Synthesis Tool for Complex Program Structures_,
2021 27th IEEE International Symposium on Asynchronous Circuits and Systems (ASYNC), 1-8,
2020.
https://ieeexplore.ieee.org/abstract/document/9565447[🔗^]

* [[[Lia23]]]
Liang, Geng-Ming and Yuan, Chuan-Yue and Yuan, Meng-Shiun and Chen, Tai-Liang and Chen, Kuan-Hsun and Lee, Jenq-Kuen,
_The Support of MLIR HLS Adaptor for LLVM IR_,
Workshop Proceedings of the 51st International Conference on Parallel Processing, 1-8,
2020.
https://doi.org/10.1145/3547276.3548515[🔗^]

* [[[Fer21]]]
+F. Ferrandi et al.,+
_Invited: Bambu: an Open-Source Research Framework for the High-Level Synthesis of Complex Applications_,
2021 58th ACM/IEEE Design Automation Conference (DAC), 1327-1330,
2021.
https://ieeexplore.ieee.org/abstract/document/9586110[🔗^]

* [[[Rot10]]]
+F. Ferrandi et al.,+
_C-to-Verilog. com: High-Level Synthesis Using LLVM_,
University of Haifa,
2010.
https://llvm.org/devmtg/2010-11/Rotem-CToVerilog.pdf[🔗^]

* [[[verugent]]]
_VeRuGent_,
Rust to Verilog: Hardware Discription DSL library,
2020.
https://github.com/RuSys/Verugent[🔗^]

* [[[rust-hdl]]]
_rust-hdl_,
Write firmware for FPGAs in Rust,
2023.
https://github.com/samitbasu/rust-hdl[🔗^]

* [[[kaze]]]
_rust-hdl_,
Generate and simulate verilog from Rust,
2022.
https://github.com/yupferris/kaze[🔗^]

* [[[Sch20]]]
Fabian Schuiki, Andreas Kurth, Tobias Grosser, and Luca Benini,
_LLHD: a multi-level intermediate representation for hardware description languages_,
In Proceedings of the 41st ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI 2020), 258–271,
2020.
https://doi.org/10.1145/3385412.3386024[🔗^]

== Temporary notes

* https://mlir.llvm.org/[MLIR^]: something from llvm, I need to look into this
* https://llhd.io/[LLHD^]: an IR for logic. VHDL <> LLHD  is like C <> LLVM IR

* https://github.com/YosysHQ/yosys[Yosys^]: This is a framework for RTL synthesis tools. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.

== Schedule

* How much time is planned for the individual central work steps?  (Research, implementation, data collection/evaluation, writing the raw text, revision and final correction)
* By when should the work be completed?