= Outline
:toc:

== Issue

Currently the source languages for HLS are usually limited subsets of C/CPP with soe additional restrictions. Rust could be a better source for HLS, because it already has some restrictions for dealing with memory that could proof beneficial for HLS. For example its semantics define memory and ownership more clearly than C/CPP.

There are some ways how toolchains for HLS from Rust can be build with currently existing tooling. However it is currently not known how viable these different toolchains would be for practical application specifically what restrictions would apply, if and how they could benefit from the additional information provided by Rust.

== Objectives and hypothesis

The main objective is to create an overview about how HLS from Rust can be achieved with state of the art technologies.

Objectives
* Create and document toolchains for HLS from Rust.
* Evaluate and compare the toolchains.
* Package the toolchains in some reusable way.
* Figure out how to leverage Rust to improve the toolchains. (maybe)

Hypotheses:
* There are ways to build toolchains for HLS from Rust by using existing tools.
* Rust can be used to improve HLS in some way.

If these objectives are fulfilled a next step could be to analyze how specific features of Rust could be used to improved.

== What needs to be done

I identified five main tasks that need to be done. 

1. Discovering possible pathways to perform HLS from Rust with existing tools.
2. Building and documenting one or more toolchains for each pathway.
3. Defining a methodology for comparing the toolchains.
4. Comparing the toolchains.
5. Analyze the results.

They could be divided into a group for creating toolchains (1, 2) and for evaluating toolchains (3, 4, 5).

== State of research

There is currently one report investigating the viability of Rust as a source for HLS <<Har22>>. The DSLX language for HLS is similar to Rust but has some limitations <<DSLX>>.

Until recently HLS was only possible from C/CPP based languages <<Nan16>>. Recently the CIRCT project from LLVM and the XLS project from google also started on building creating flexible systems for HLS <<XLS>> <<Nor18>>.

There also is research on performing HLS from LLVM IR. Specifically the LLVM CIRCT project has worked on HLS.

== About Bibliography

Searched google scholar for `rust high level synthesis`, looked at first 5 pages, copied all entries related to rust programming and HLS to bibliography. <<Har22>> <<Tak20>>

Searched google scholar for `llvm high level synthesis. <<Rog20>> <<Li20>> <<Lia23>>

Searched google scholar for `high level synthesis. <<Rot10>> <<Fer21>>

https://crates.io is the primary rust package registry. If someone has already done some work in rust it will be on there. I list crates with their name, description from cargo.toml, and date of last commit.

I tried to find projects that already do HLS from rust.

For all https://crates.io searches I looked at all results, selected everything that is related to generating RTL from rust, is not hardware specific, is not a opencl wrapper, is not related to interfacing with FPGAs, and is not a extension for another already listed result.


Searched https://crates.io 

* `high level synthesis`: <<verugent>>
* `hls`: -
* `fpga`: <<rust-hdl>> <<kaze>>
* `hld`: -

The only one of these crates that does something that is similar to HLS is rust-hdl, but that is more like a HDL and less HLS, because it only supports a limited subset of rust.

So there is no tool for performing HLS from rust on crates.io.

I tried to search google for other ways of performing HLS directly from rust.

.Google searches
[%collapsible]
====
I visited the following pages:

* https://users.rust-lang.org/t/rust-and-fpgas-is-it-possible/50033/5
** Reference to <<Tak20>>
** Reference to https://google.github.io/xls/[XLS^] which is a more generic solution
** Reference to https://github.com/llvm/circt[CIRCT^] which is a llvm project about Circuit IR Compilers and Tools. LLHD belongs to CIRCT.
** There apparently are already a few llvm ir to fpga tools. Very interesting link: https://llvm.org/devmtg/2014-10/Slides/Baker-CustomHardwareStateMachines.pdf
* https://www.reddit.com/r/rust/comments/fyd57q/q_rust_as_a_hardware_description_language_to_be/
** LLVM is probably the easiest way.
** _"My thinking is that Rust code would be much more efficient than OpenCL since it should naturally prevent latching."_
** https://www.chisel-lang.org/firrtl/[FIRRTL^] is called the _"most developed low-level HDL intermediate language"_ (2020)
** Also references <<Tak20>>
** Link the LLHD paper. I added it to my bib <<Sch20>>
* https://www.youtube.com/watch?v=TUDkKxAdeWk
** Maybe there is something interesting in this video, but I dont think so.
** TODO: watch
* https://ieeexplore.ieee.org/document/9292032
** The paper is related to <<verugent>>. Horrible english.
** Same author as <<Tak20>>
** Not related, because verugent is just a verilog builder, but does not do HLS.
* https://news.ycombinator.com/item?id=24354083
** About XLS
** XLS is a HDL that is based on Rust, I think
** https://google.github.io/xls/dslx_reference/[DSLX] is the language, XLS is just the framework
** https://github.com/google/xls/blob/main/xls/examples/dslx_intro/prefix_scan_equality.x[Some code]
====

Through the google search I found XLS, which is probably similar to <<rust-hdl>>, but may have more HLS capabilities. It is not real Rust, but syntactically and semantically inspired by Rust.

TODO: investigate XLS

The only remaining way of synthesizing Rust I can think of is maybe with some port of opencl that also has a FPGA backend. If that would be the case than I probably would have found it in the previous google search. Most HPC frameworks like openmp build on top of opencl, so if opencl cannot bring Rust to FPGAs, they also wont be able to do that. Anyway I will now specifically search for `rust opencl`.

opencl has a rust port, but the kernels still have to be written in C++. Maybe there is another path to fpgas by compiling to a shader language and then to fpga somehow. trisycl.

There is currently no way of synthesising RTL from normal Rust directly. With rust-hdl and XLS there are two approaches, but both are limited indifferent ways. I dont think I missed anything.

Next step would be to look at some intermediate representations.

[bibliography]
== Bibliography

* [[[Har22]]]
Hardin, David,
_Hardware/Software Co-Assurance using the Rust Programming Language and ACL2_,
arXiv preprint arXiv:2205.11709,
2022.
https://arxiv.org/abs/2205.11709v1[🔗^]

* [[[Tak20]]]
Takano, Keisuke and Oda, Tetsuya and Kohata, Masaki,
_Design of a DSL for converting rust programming language into RTL_,
International Conference on Emerging Internetworking, Data & Web Technologies, 342-350,
2020.
https://link.springer.com/chapter/10.1007/978-3-030-39746-3_36[🔗^]

* [[[Rog20]]]
Rogers, Samuel and Slycord, Joshua and Baharani, Mohammadreza and Tabkhi, Hamed,
_gem5-SALAM: A System Architecture for LLVM-based Accelerator Modeling_,
2020 53rd Annual IEEE/ACM International Symposium on Microarchitecture (MICRO), 471-482,
2020.
https://ieeexplore.ieee.org/abstract/document/9251937[🔗^]

* [[[Li21]]]
Li, Rui and Berkley, Lincoln and Yang, Yihang and Manohar, Rajit,
_Fluid: An Asynchronous High-level Synthesis Tool for Complex Program Structures_,
2021 27th IEEE International Symposium on Asynchronous Circuits and Systems (ASYNC), 1-8,
2020.
https://ieeexplore.ieee.org/abstract/document/9565447[🔗^]

* [[[Lia23]]]
Liang, Geng-Ming and Yuan, Chuan-Yue and Yuan, Meng-Shiun and Chen, Tai-Liang and Chen, Kuan-Hsun and Lee, Jenq-Kuen,
_The Support of MLIR HLS Adaptor for LLVM IR_,
Workshop Proceedings of the 51st International Conference on Parallel Processing, 1-8,
2020.
https://doi.org/10.1145/3547276.3548515[🔗^]

* [[[Fer21]]]
+F. Ferrandi et al.,+
_Invited: Bambu: an Open-Source Research Framework for the High-Level Synthesis of Complex Applications_,
2021 58th ACM/IEEE Design Automation Conference (DAC), 1327-1330,
2021.
https://ieeexplore.ieee.org/abstract/document/9586110[🔗^]

* [[[Rot10]]]
+F. Ferrandi et al.,+
_C-to-Verilog. com: High-Level Synthesis Using LLVM_,
University of Haifa,
2010.
https://llvm.org/devmtg/2010-11/Rotem-CToVerilog.pdf[🔗^]

* [[[verugent]]]
_VeRuGent_,
Rust to Verilog: Hardware Discription DSL library,
2020.
https://github.com/RuSys/Verugent[🔗^]

* [[[rust-hdl]]]
_rust-hdl_,
Write firmware for FPGAs in Rust,
2023.
https://github.com/samitbasu/rust-hdl[🔗^]

* [[[kaze]]]
_rust-hdl_,
Generate and simulate verilog from Rust,
2022.
https://github.com/yupferris/kaze[🔗^]

* [[[Sch20]]]
Fabian Schuiki, Andreas Kurth, Tobias Grosser, and Luca Benini,
_LLHD: a multi-level intermediate representation for hardware description languages_,
In Proceedings of the 41st ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI 2020), 258–271,
2020.
https://doi.org/10.1145/3385412.3386024[🔗^]

* [[[Nan16]]]
R. Nane et al.,
_A Survey and Evaluation of FPGA High-Level Synthesis Tools_,
IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems, 1591-1604,
2016.
https://ieeexplore.ieee.org/abstract/document/7368920[🔗^]

* [[[Nor18]]]
D. H. Noronha, B. Salehpour and S. J. E. Wilton,
_LeFlow: Enabling Flexible FPGA High-Level Synthesis of Tensorflow Deep Neural Networks_,
Fifth International Workshop on FPGAs for Software Programmers, 1-8,
2018.
https://ieeexplore.ieee.org/abstract/document/8470462[🔗^]

* [[Soz22]]
Sozzo, Emanuele Del, et al.,
_Pushing the level of abstraction of digital system design: A survey on how to program FPGAs_,
ACM Computing Surveys, 1-48,
2022.
https://dl.acm.org/doi/abs/10.1145/3532989[🔗^]

* [[XLS]]
_XLS project page_
https://google.github.io/xls/[🔗^]

* [[DSLX]]
_DSLX Reference_
https://google.github.io/xls/dslx_reference/[🔗^]


== Temporary notes

* https://mlir.llvm.org/[MLIR^]: something from llvm, I need to look into this
* https://llhd.io/[LLHD^]: an IR for logic. VHDL <> LLHD  is like C <> LLVM IR

* https://github.com/YosysHQ/yosys[Yosys^]: This is a framework for RTL synthesis tools. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.