= Other HLS systems/frameworks/toolchains

== Chisel

Chisel is a hardware construction language for constructing digital circuits. It is a Scala library that allows you to write hardware descriptions in a Scala-like language. Compiles scala files to FIRRTL IR files, which can be converted to Verilog using FIRRTL. FIRRTL also provides some transformations that can be used to transform and optimize the IR before converting to Verilog.

== CIRCT

LLVM subproject. Goal is to apply the benefits of modular library based design learned from LLVM to hardware design. MLIR based tech for Hardware design and verification.

== MLIR

MLIR is a multi-paradigm IR for representing and manipulating hardware designs. It is a library that provides a common IR, a set of transformations, and a set of tools to build tools for hardware design and verification. MLIR is a part of the LLVM project.

== MHAL ?

== ahaHLS

Research prototype for HLS from LLVM IR. Inactive project for four years, but still seems to work. Maybe worth a look. Has no CLI, but can be used as a library. Afaik no documentation except for a https://www.dillonbhuff.com/?p=1907[blog post]. Maybe there is a paper somewhere. Seems to support algorithmic C only, but I am not sure.

== PandA bambu

FOSS hls framework. Can process llvm. Installing is difficult.

== Gaut

FOSS hls framework. Cannot process llvm.

== Dynamatic

toolchain and LLVM passes to convert llvm IR to VHDL. No cli tool, I think.

https://github.com/lana555/dynamatic

== Hastlayer

Something like HLS for .NET binaries. Does not use LLVM, at least searching their repo for "llvm" does not yield any results.

== LegUp

HLS tool. Only source-available, not FOSS. idk if it can process LLVM IR.

== Roccc

HLS tool I think. FOSS. Should be based on LLVM. Last commit was in 2015, but it looks like it could work.

https://github.com/nxt4hll/roccc-2.0

== XLS

HLS tool. FOSS. Active development. Has own HLS language, DSLX. Uses LLVM somewhere in the process.

== Shang


HLS tool. No license. Based on LLVM. Last commit was 10 years ago.
