ifndef::env-vscode[]
:env-not-vscode: 
endif::env-vscode[]
ifdef::backend-html5+env-not-vscode[]
:vega-as-script:
endif::backend-html5+env-not-vscode[]

// Define the filename as 

ifndef::vega-lite-filename[]
[IMPORTANT]
.Missing source file for vega chart
====
You need to defined the source file as `:vega-lite-filename:`

.Example:
----
:vega-lite-filename: my-chart.vl.json
++include::vega-lite.adoc[]++
----
====
endif::vega-lite-filename[]

ifdef::vega-lite-filename[]
ifdef::vega-as-script[]
// Embed the script as js if we are running in a browser
++++
    <div class="diagram"></div>
    <script>
      if(
        !document.vegaLoaded &&
        document.querySelector('script[src="https://cdn.jsdelivr.net/npm/vega@5.22.1"]') &&
        document.querySelector('script[src="https://cdn.jsdelivr.net/npm/vega-lite@5.6.0"]') &&
        document.querySelector('script[src="https://cdn.jsdelivr.net/npm/vega-embed@6.21.0"]')
      ){
        document.vegaLoaded = Promise.resolve();
      }
      
      if(!document.vegaLoaded) {
        console.log('Loading vega dynamically. Consider adding');
        console.log('<script src="https://cdn.jsdelivr.net/npm/vega@5.22.1"><\/script>\n<script src="https://cdn.jsdelivr.net/npm/vega-lite@5.6.0"><\/script>\n<script src="https://cdn.jsdelivr.net/npm/vega-embed@6.21.0"><\/script>');
        console.log('to docinfo.html');
        var scriptA = document.createElement('script');
        scriptA.type = 'text/javascript';
        scriptA.src = 'https://cdn.jsdelivr.net/npm/vega@5.22.1';    
        var scriptB = document.createElement('script');
        scriptB.type = 'text/javascript';
        scriptB.src = 'https://cdn.jsdelivr.net/npm/vega-lite@5.6.0';    
        var scriptC = document.createElement('script');
        scriptC.type = 'text/javascript';
        scriptC.src = 'https://cdn.jsdelivr.net/npm/vega-embed@6.21.0';    

        document.vegaLoaded = Promise.all([
          new Promise((resolve, reject) => {
            scriptA.onload = () => {
              document.head.appendChild(scriptB);
              resolve();
            };
            scriptA.onerror = reject;
          }),
          new Promise((resolve, reject) => {
            scriptB.onload = () => {
              document.head.appendChild(scriptC);
              resolve();
            };
            scriptB.onerror = reject;
          }),
          new Promise((resolve, reject) => {
            scriptC.onload = resolve;
            scriptC.onerror = reject;
          })]
        );

        document.head.appendChild(scriptA);

      }

     (() => {
      const thisScript = document.currentScript;
      

      // Assign the specification to a local variable vlSpec.
      const vlSpec =

include::{vega-lite-filename}[]

      ;
      const container = thisScript.previousElementSibling;
      const containerId = new Array(20).fill().map(() => Math.random().toString(36)[2]).join('');
      container.id = containerId;

      (async () => {
        await document.vegaLoaded;
        vegaEmbed(`#${containerId}`, vlSpec);
      })();
      })();
    </script>
++++
endif::vega-as-script[]
ifndef::vega-as-script[]
// Embed the script with asciidoctor-diagram if we are running in vscode
[vegalite]
....
include::{vega-lite-filename}[]
....
endif::vega-as-script[]
endif::vega-lite-filename[]
