# This file has been generated by node2nix 1.11.1. Do not edit!

{ pkgs ? import <nixpkgs> { } }:

with pkgs;
rustPlatform.buildRustPackage rec {
  pname = "test-toolchain";
  version = "0.1.0";

  src = ./.;

  nativeBuildInputs = [
    rustfmt
  ];
  RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";


  cargoLock = {
    lockFile = ./Cargo.lock;
  };
}
