[package]
name = "rust_hls_example"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-hdl = "0.45.1"
rust_hls_macro = { path = "../rust_hls_macro", version = "0.2.0" }

[build-dependencies]
rust_hls = { path = "../rust_hls", features = ["verilator"], version = "0.2.0" }
