= Introduction to High-Level Synthesis from Rust
:last-update-label!:
:imagesdir: images
:source-highlighter: rouge
:rouge-style: github
:cpp: C++
:toclevels: 2
:docinfo: shared,private-footer
:stem:
:toc: macro

Fellow Rustaceans, embark on a journey with me, into the enchanted world of hardware design.

With FPGAs, we'll transcend the limitations of traditional CPUs, unlocking faster and more efficient calculations. Our journey will be a perilous one, as the language of FPGAs and the common programming languages of our world are vastly different. It would need a mighty sorcerer to bridge that gap. Maybe even multiple ones. The path ahead is unclear, but we shall not be deterred.

In the labyrinthine passages of the internet, we shall search for answers. We will encounter PandA, an experienced high-level synthesizer. This powerful entity can translate the ancient languages of C/{cpp} into descriptive forms that the FPGAs can understand. Yet, even PandA is unable to understand our native tongue, Rust. Fear not, brave adventurer, for we have the aid of a mighty and swift wyvern of LLVM. It set out to create a common language, not to be natively spoken by anyone, but to be understood by all. We will use the language of LLVM to communicate with PandA, and see how it fares with our Rust compared to its familiar C/{cpp}. So gather your courage and sharpen your wits, for our journey into the mystical world of HLS, FPGAs, CPUs, and LLVM is about to begin.

toc::[]

== Introduction