[package]
name = "rust-keccak"
description = "Rust keccak function for benchmarking."
version = "0.1.0"
edition = "2021"

[dependencies]
keccak_crates_io = { version = "0.1.4", package = "keccak" }
seq-macro = "0.3.3"
